// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_alexm99.Models;

namespace Mission06_alexm99.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230210204124_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_alexm99.Models.Movies", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Comedy,Adventure",
                            Director = "Terry Gilliam, Terry Jones",
                            Edited = false,
                            Lent_To = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Monty Python and the Holy Grail",
                            Year = 1975
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action,Crime,Music",
                            Director = "Edgar Wright",
                            Edited = false,
                            Lent_To = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Baby Driver",
                            Year = 2017
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action, Thriller",
                            Director = "Chad Stahelski",
                            Edited = false,
                            Lent_To = "",
                            Notes = "",
                            Rating = "R",
                            Title = "John Wick",
                            Year = 2014
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
