// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_alexm99.Models;

namespace Mission06_alexm99.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_alexm99.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryType")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryType = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryType = "Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryType = "Adventure"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryType = "Mystery"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryType = "Crime"
                        });
                });

            modelBuilder.Entity("Mission06_alexm99.Models.Movies", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 2,
                            Director = "Terry Gilliam, Terry Jones",
                            Edited = false,
                            Lent_To = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Monty Python and the Holy Grail",
                            Year = 1975
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 5,
                            Director = "Edgar Wright",
                            Edited = false,
                            Lent_To = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Baby Driver",
                            Year = 2017
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 1,
                            Director = "Chad Stahelski",
                            Edited = false,
                            Lent_To = "",
                            Notes = "",
                            Rating = "R",
                            Title = "John Wick",
                            Year = 2014
                        });
                });

            modelBuilder.Entity("Mission06_alexm99.Models.Movies", b =>
                {
                    b.HasOne("Mission06_alexm99.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
